In [4]:
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369


In [7]:
def vector_multiplicacion(u,v):
    assert u.shape[0]==v.shape[0]
    n=u.shape[0]
    result=0.0
    
    for i in range(n): #n-1 es el tamaño real de la matriz 
        result=result+u[i]*v[i]
        
    return result
    

In [17]:
import numpy as np
u=np.array([1,2,3])
v=np.array([9,8,7])


In [18]:
vector_multiplicacion(u,v)

np.float64(46.0)

In [19]:
U=np.random.randint(0, 10, size=(5, 3))
U

array([[7, 5, 4],
       [5, 2, 0],
       [0, 5, 6],
       [1, 7, 8],
       [0, 5, 8]])

In [22]:
#el numero de columnas de U debe de coincidir con el numero de filas v 
def matrix_vector_multiplicacion(U,v):
    assert U.shape[1]== v.shape[0]
    num_rows=U.shape[0]
    result=np.zeros(num_rows)
    for i in range(num_rows):
        result[i]=vector_multiplicacion(U[i], v)
    return result

In [23]:
matrix_vector_multiplicacion(U,v)

array([131.,  61.,  82., 121.,  96.])

In [ ]:
U.dot(v) # esta es la funcion paraa matricz vector

array([131,  61,  82, 121,  96])

In [34]:
V=np.random.randint(10,20, size=(3,5))
V

array([[12, 11, 14, 15, 10],
       [17, 11, 11, 17, 15],
       [14, 12, 19, 15, 19]])

In [61]:
def matrix_matrix_multplicación(U,V):
    assert U.shape[1]== V.shape[0]
    num_rows=U.shape[1]
    num_colums=V.shape[0]
    print(num_rows,num_colums)
    result=np.zeros((num_rows, num_colums))
    for i in range(num_rows):
            vi = V[i, :]
            Uvi = vector_multiplicacion(U, vi) # Asegúrate de que esta función esté definida
            result[i, :] = Uvi
            
    return result

In [62]:
matrix_matrix_multplicación(U, V)

3 3


array([[154., 307., 332.],
       [191., 356., 390.],
       [173., 389., 442.]])

In [65]:
U.dot(V)

array([[225, 180, 229, 250, 221],
       [ 94,  77,  92, 109,  80],
       [169, 127, 169, 175, 189],
       [243, 184, 243, 254, 267],
       [197, 151, 207, 205, 227]])

In [66]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [70]:
I=np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
V.dot(I)

array([[12., 11., 14., 15., 10.],
       [17., 11., 11., 17., 15.],
       [14., 12., 19., 15., 19.]])

In [87]:
Vs=V[:,:3]
Vs

array([[12, 11, 14],
       [17, 11, 11],
       [14, 12, 19]])

In [88]:
Vs_inv=np.linalg.inv(Vs)
Vs_inv

array([[-0.32765957,  0.17446809,  0.14042553],
       [ 0.71914894, -0.13617021, -0.45106383],
       [-0.21276596, -0.04255319,  0.23404255]])

In [89]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='str')

In [95]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   str    
 7   fuel_type            9704 non-null   str    
 8   drivetrain           9704 non-null   str    
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), str(3)
memory usage: 834.1 KB


In [96]:
df.origin

0       Europe
1          USA
2       Europe
3          USA
4       Europe
         ...  
9699    Europe
9700       USA
9701       USA
9702       USA
9703      Asia
Name: origin, Length: 9704, dtype: str

In [97]:
df.index

RangeIndex(start=0, stop=9704, step=1)

In [1]:
df.loc[1]

NameError: name 'df' is not defined